### ISSUE TITLE
Lost controls for Waterfall and Spa Jets, pumps.

### ISSUE THREAD

**Issue by MHillyer** [djtimca/haomnilogic#1]
Hi There,

Thanks for moving this to HACS, glad to finally see controls for the lights and heater!

Unlike the previous install in core I am noticing a lack of controls for the pumps as well as waterfall in HomeAssistant. Not sure what you need to help troubleshoot it but happy to provide whatever is needed.

**Comment by djtimca** [comment]
Can you send a screen shot of what you see in the Device page in Home Assistant to start so I can see what devices it is picking up. 

The only thing that ever made it into core was the sensors so it must be something from a previous version of our custom components that worked (and obviously I since broke). 

Will get it sorted... at least here we don't have to wait for approvals!

**Comment by MHillyer** [comment]
Lot of alarms, no switches.

**Comment by MHillyer** [comment]
Screenshot happened too soon after a restart, they all say Off now aside from the pump speeds that read unavailable because those pumps are off.

**Comment by djtimca** [comment]
OK - are you able to generate an output file for me by going to: https://replit.com/@djtimca/OmniTesting#main.py

Hit run at the top, log in with your Hayward credentials, then hit enter to clear. Nothing is stored except the telemetry output.

**Comment by MHillyer** [comment]
Done.

**Comment by MHillyer** [comment]
I've seen that too, I wonder if shortening the pooling window would help that.
